### ISSUE TITLE
Prerendering restriction: EME

### ISSUE THREAD

**Issue by mfalken** [jeremyroman/alternate-loading-modes#61]
At https://github.com/jeremyroman/alternate-loading-modes/pull/45 we previously decided to always defer reject/resolve of a promise, even for immutable checks that could be run before prerendering.

I started looking at this for EME: https://w3c.github.io/encrypted-media/#requestMediaKeySystemAccess

In Blink it looks like it would be slightly inconvenient to take that approach as seen in this CL: https://chromium-review.googlesource.com/c/chromium/src/+/2874764

Blink currently does all the sync checks first, returning a new promise or throwing an exception. Only after that is done does 
it makes a promise to be resolved after the async work. 
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/encryptedmedia/navigator_request_media_key_system_access.cc;l=128;drc=7fcda909a4f438f251cf98d93cf494efe35b1bd7

This actually matches the spec text fairly closely: https://w3c.github.io/encrypted-media/#requestMediaKeySystemAccess

For this case, I wonder if it'd make sense to just defer after the "Let promise be a new promise." point. But this would be inconsistent with the earlier decision in the above PR.

I'm also wondering if there is a difference between `throw a [exception] and abort these steps` and `return a promise rejected with a newly created [error]` as in the Step 1 vs Step 2 of the requestMediaKeySystemAccess() algorithm. In Blink it looks identical, both cases do: 

```javascript
 exception_state.Throw*Error();
 return ScriptPromise();
```

Any thoughts on this? @domenic @jeremyroman

**Comment by mfalken** [comment]
I suppose the difference of "throw an exception" vs "return a promise rejected with an error" is as follows:

```javascript
let promise;
try {
  promise = requestMediaAccess();
} catch (e) {
  console.log('threw synchronously');
}

try {
  if (promise)
    await promise;
} catch (e) {
  console.log('rejected the promise with error');
}
```

Step 1 failing should cause 'threw synchronously' to be printed and Step 2 would be 'rejected the promise with error', but maybe Blink isn't adhering to the spec here.

**Comment by domenic** [comment]
> I'm also wondering if there is a difference between throw a [exception] and abort these steps and return a promise rejected with a newly created [error] as in the Step 1 vs Step 2 of the requestMediaKeySystemAccess() algorithm. In Blink it looks identical, both cases do:

This is a spec bug to some extent.

Promise-returning functions cannot throw exceptions. This is enforced in Web IDL; any thrown exceptions get converted into returned rejected promises. This is the same as how Blink's binding generator behaves.

However, it's bad practice when writing a spec to use "throw an exception" in a promise-returning function, because it's so confusing in cases like this. Specs should always use "return a promise rejected with..."

So, there is no difference.

> Any thoughts on this?

I'd prefer consistency, personally. Either direction would be OK: either do all the early checks before deferral, or do them after.

I guess after deferral is a bit better because some of the early checks might fail in a prerendering browsing context but succeed once activated. E.g. I think some APIs check "is this the currently focused top-level browsing context".

I do think after-deferral is probably going to be a bit harder to implement in Blink due to our style of throwing exceptions and having the bindings infrastructure convert those into rejected promises. But I'm not sure we should change the spec based on that.

**Comment by jeremyroman** [comment]
@domenic already said what I was going to say, but better. Especially the key point that anything that exceptions thrown from promise-returning operations are always turned into rejections, so the `"threw synchronously"` case can never happen.

**Comment by mfalken** [comment]
Thanks that all makes sense. That actually makes things nicer I think, that we don't need to worry about sync vs async checks.

I also prefer consistency here. I agree if we do allow rejecting before activation, it should only be for immutable checks. There are some trivial ones like "reject if `param` is the empty string" which feels unnecessarily slow to defer. On the other hand, it's really easy to understand "the promise will never settle until after activation".
